CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpAuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NULL,
        "ServiceName" character varying(256) NULL,
        "MethodName" character varying(256) NULL,
        "Parameters" character varying(1024) NULL,
        "ReturnValue" text NULL,
        "ExecutionTime" timestamp without time zone NOT NULL,
        "ExecutionDuration" integer NOT NULL,
        "ClientIpAddress" character varying(64) NULL,
        "ClientName" character varying(128) NULL,
        "BrowserInfo" character varying(512) NULL,
        "ExceptionMessage" character varying(1024) NULL,
        "Exception" character varying(2000) NULL,
        "ImpersonatorUserId" bigint NULL,
        "ImpersonatorTenantId" integer NULL,
        "CustomData" character varying(2000) NULL,
        CONSTRAINT "PK_AbpAuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpBackgroundJobs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "JobType" character varying(512) NOT NULL,
        "JobArgs" character varying(1048576) NOT NULL,
        "TryCount" smallint NOT NULL,
        "NextTryTime" timestamp without time zone NOT NULL,
        "LastTryTime" timestamp without time zone NULL,
        "IsAbandoned" boolean NOT NULL,
        "Priority" smallint NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpBackgroundJobs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpDynamicProperties" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyName" character varying(256) NULL,
        "DisplayName" text NULL,
        "InputType" text NULL,
        "Permission" text NULL,
        "TenantId" integer NULL,
        CONSTRAINT "PK_AbpDynamicProperties" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpEditions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(32) NOT NULL,
        "DisplayName" character varying(64) NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpEditions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpEntityChangeSets" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "BrowserInfo" character varying(512) NULL,
        "ClientIpAddress" character varying(64) NULL,
        "ClientName" character varying(128) NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "ExtensionData" text NULL,
        "ImpersonatorTenantId" integer NULL,
        "ImpersonatorUserId" bigint NULL,
        "Reason" character varying(256) NULL,
        "TenantId" integer NULL,
        "UserId" bigint NULL,
        CONSTRAINT "PK_AbpEntityChangeSets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpLanguages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Name" character varying(128) NOT NULL,
        "DisplayName" character varying(64) NOT NULL,
        "Icon" character varying(128) NULL,
        "IsDisabled" boolean NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpLanguages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpLanguageTexts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "LanguageName" character varying(128) NOT NULL,
        "Source" character varying(128) NOT NULL,
        "Key" character varying(256) NOT NULL,
        "Value" text NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        CONSTRAINT "PK_AbpLanguageTexts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpNotifications" (
        "Id" uuid NOT NULL,
        "NotificationName" character varying(96) NOT NULL,
        "Data" character varying(1048576) NULL,
        "DataTypeName" character varying(512) NULL,
        "EntityTypeName" character varying(250) NULL,
        "EntityTypeAssemblyQualifiedName" character varying(512) NULL,
        "EntityId" character varying(96) NULL,
        "Severity" smallint NOT NULL,
        "UserIds" character varying(131072) NULL,
        "ExcludedUserIds" character varying(131072) NULL,
        "TenantIds" character varying(131072) NULL,
        "TargetNotifiers" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpNotificationSubscriptions" (
        "Id" uuid NOT NULL,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "NotificationName" character varying(96) NULL,
        "EntityTypeName" character varying(250) NULL,
        "EntityTypeAssemblyQualifiedName" character varying(512) NULL,
        "EntityId" character varying(96) NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpNotificationSubscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpOrganizationUnitRoles" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "RoleId" integer NOT NULL,
        "OrganizationUnitId" bigint NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpOrganizationUnitRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpOrganizationUnits" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ParentId" bigint NULL,
        "Code" character varying(95) NOT NULL,
        "DisplayName" character varying(128) NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpOrganizationUnits" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpOrganizationUnits_AbpOrganizationUnits_ParentId" FOREIGN KEY ("ParentId") REFERENCES "AbpOrganizationUnits" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpTenantNotifications" (
        "Id" uuid NOT NULL,
        "TenantId" integer NULL,
        "NotificationName" character varying(96) NOT NULL,
        "Data" character varying(1048576) NULL,
        "DataTypeName" character varying(512) NULL,
        "EntityTypeName" character varying(250) NULL,
        "EntityTypeAssemblyQualifiedName" character varying(512) NULL,
        "EntityId" character varying(96) NULL,
        "Severity" smallint NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpTenantNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserAccounts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "UserLinkId" bigint NULL,
        "UserName" character varying(256) NULL,
        "EmailAddress" character varying(256) NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpUserAccounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserLoginAttempts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "TenancyName" character varying(64) NULL,
        "UserId" bigint NULL,
        "UserNameOrEmailAddress" character varying(256) NULL,
        "ClientIpAddress" character varying(64) NULL,
        "ClientName" character varying(128) NULL,
        "BrowserInfo" character varying(512) NULL,
        "Result" smallint NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_AbpUserLoginAttempts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserNotifications" (
        "Id" uuid NOT NULL,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "TenantNotificationId" uuid NOT NULL,
        "State" integer NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "TargetNotifiers" text NULL,
        CONSTRAINT "PK_AbpUserNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserOrganizationUnits" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "OrganizationUnitId" bigint NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpUserOrganizationUnits" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUsers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        "AuthenticationSource" character varying(64) NULL,
        "UserName" character varying(256) NOT NULL,
        "TenantId" integer NULL,
        "EmailAddress" character varying(256) NOT NULL,
        "Name" character varying(64) NOT NULL,
        "Surname" character varying(64) NOT NULL,
        "Password" character varying(128) NOT NULL,
        "EmailConfirmationCode" character varying(328) NULL,
        "PasswordResetCode" character varying(328) NULL,
        "LockoutEndDateUtc" timestamp without time zone NULL,
        "AccessFailedCount" integer NOT NULL,
        "IsLockoutEnabled" boolean NOT NULL,
        "PhoneNumber" character varying(32) NULL,
        "IsPhoneNumberConfirmed" boolean NOT NULL,
        "SecurityStamp" character varying(128) NULL,
        "IsTwoFactorEnabled" boolean NOT NULL,
        "IsEmailConfirmed" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "NormalizedUserName" character varying(256) NOT NULL,
        "NormalizedEmailAddress" character varying(256) NOT NULL,
        "ConcurrencyStamp" character varying(128) NULL,
        CONSTRAINT "PK_AbpUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpUsers_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpUsers_AbpUsers_DeleterUserId" FOREIGN KEY ("DeleterUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpUsers_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpWebhookEvents" (
        "Id" uuid NOT NULL,
        "WebhookName" text NOT NULL,
        "Data" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "TenantId" integer NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpWebhookEvents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpWebhookSubscriptions" (
        "Id" uuid NOT NULL,
        "TenantId" integer NULL,
        "WebhookUri" text NOT NULL,
        "Secret" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "Webhooks" text NULL,
        "Headers" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpWebhookSubscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpDynamicEntityProperties" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityFullName" character varying(256) NULL,
        "DynamicPropertyId" integer NOT NULL,
        "TenantId" integer NULL,
        CONSTRAINT "PK_AbpDynamicEntityProperties" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpDynamicEntityProperties_AbpDynamicProperties_DynamicProp~" FOREIGN KEY ("DynamicPropertyId") REFERENCES "AbpDynamicProperties" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpDynamicPropertyValues" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Value" text NOT NULL,
        "TenantId" integer NULL,
        "DynamicPropertyId" integer NOT NULL,
        CONSTRAINT "PK_AbpDynamicPropertyValues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpDynamicPropertyValues_AbpDynamicProperties_DynamicProper~" FOREIGN KEY ("DynamicPropertyId") REFERENCES "AbpDynamicProperties" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpFeatures" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Name" character varying(128) NOT NULL,
        "Value" character varying(2000) NOT NULL,
        "Discriminator" text NOT NULL,
        "EditionId" integer NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpFeatures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpFeatures_AbpEditions_EditionId" FOREIGN KEY ("EditionId") REFERENCES "AbpEditions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpEntityChanges" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ChangeTime" timestamp without time zone NOT NULL,
        "ChangeType" smallint NOT NULL,
        "EntityChangeSetId" bigint NOT NULL,
        "EntityId" character varying(48) NULL,
        "EntityTypeFullName" character varying(192) NULL,
        "TenantId" integer NULL,
        CONSTRAINT "PK_AbpEntityChanges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpEntityChanges_AbpEntityChangeSets_EntityChangeSetId" FOREIGN KEY ("EntityChangeSetId") REFERENCES "AbpEntityChangeSets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpRoles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Description" character varying(5000) NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        "TenantId" integer NULL,
        "Name" character varying(32) NOT NULL,
        "DisplayName" character varying(64) NOT NULL,
        "IsStatic" boolean NOT NULL,
        "IsDefault" boolean NOT NULL,
        "NormalizedName" character varying(32) NOT NULL,
        "ConcurrencyStamp" character varying(128) NULL,
        CONSTRAINT "PK_AbpRoles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpRoles_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpRoles_AbpUsers_DeleterUserId" FOREIGN KEY ("DeleterUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpRoles_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpSettings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NULL,
        "Name" character varying(256) NOT NULL,
        "Value" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        CONSTRAINT "PK_AbpSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpSettings_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpTenants" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        "TenancyName" character varying(64) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "ConnectionString" character varying(1024) NULL,
        "IsActive" boolean NOT NULL,
        "EditionId" integer NULL,
        CONSTRAINT "PK_AbpTenants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpTenants_AbpEditions_EditionId" FOREIGN KEY ("EditionId") REFERENCES "AbpEditions" ("Id"),
        CONSTRAINT "FK_AbpTenants_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpTenants_AbpUsers_DeleterUserId" FOREIGN KEY ("DeleterUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_AbpTenants_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserClaims" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "ClaimType" character varying(256) NULL,
        "ClaimValue" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpUserClaims_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserLogins" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "LoginProvider" character varying(128) NOT NULL,
        "ProviderKey" character varying(256) NOT NULL,
        CONSTRAINT "PK_AbpUserLogins" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpUserLogins_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserRoles" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "RoleId" integer NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpUserRoles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpUserRoles_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpUserTokens" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "LoginProvider" character varying(128) NULL,
        "Name" character varying(128) NULL,
        "Value" character varying(512) NULL,
        "ExpireDate" timestamp without time zone NULL,
        CONSTRAINT "PK_AbpUserTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpUserTokens_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "Contacts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "CompanyName" text NULL,
        "CustomerName" text NULL,
        "Phone" text NULL,
        "Email" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contacts_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_Contacts_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractBase64Images" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractId" bigint NOT NULL,
        "ContractPage" integer NOT NULL,
        "FileBase64" text NULL,
        "Width" real NOT NULL,
        "Height" real NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractBase64Images" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractBase64Images_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractBase64Images_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "Contracts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "Name" text NULL,
        "EmailContent" text NULL,
        "Code" text NULL,
        "File" text NULL,
        "FileBase64" text NULL,
        "Status" integer NOT NULL,
        "ExpriredTime" timestamp without time zone NULL,
        "ContractTemplateId" bigint NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_Contracts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contracts_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_Contracts_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_Contracts_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractTemplates" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Name" text NULL,
        "FileName" text NULL,
        "Content" text NULL,
        "HtmlContent" text NULL,
        "Type" integer NOT NULL,
        "UserId" bigint NULL,
        "IsFavorite" boolean NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractTemplates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractTemplates_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractTemplates_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "EmailTemplates" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Name" text NULL,
        "BodyMessage" text NULL,
        "Subject" text NULL,
        "Description" character varying(1000) NULL,
        "Type" integer NOT NULL,
        "CCs" character varying(200) NULL,
        "SendToEmail" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_EmailTemplates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailTemplates_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_EmailTemplates_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "SignatureUsers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "SignatureTypeId" bigint NOT NULL,
        "SignatureType" integer NOT NULL,
        "UserId" bigint NOT NULL,
        "File" text NULL,
        "FileBase64" text NULL,
        "IsDefault" boolean NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_SignatureUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SignatureUsers_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_SignatureUsers_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_SignatureUsers_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpWebhookSendAttempts" (
        "Id" uuid NOT NULL,
        "WebhookEventId" uuid NOT NULL,
        "WebhookSubscriptionId" uuid NOT NULL,
        "Response" text NULL,
        "ResponseStatusCode" integer NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "TenantId" integer NULL,
        CONSTRAINT "PK_AbpWebhookSendAttempts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpWebhookSendAttempts_AbpWebhookEvents_WebhookEventId" FOREIGN KEY ("WebhookEventId") REFERENCES "AbpWebhookEvents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpDynamicEntityPropertyValues" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Value" text NOT NULL,
        "EntityId" text NULL,
        "DynamicEntityPropertyId" integer NOT NULL,
        "TenantId" integer NULL,
        CONSTRAINT "PK_AbpDynamicEntityPropertyValues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpDynamicEntityPropertyValues_AbpDynamicEntityProperties_D~" FOREIGN KEY ("DynamicEntityPropertyId") REFERENCES "AbpDynamicEntityProperties" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpEntityPropertyChanges" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EntityChangeId" bigint NOT NULL,
        "NewValue" character varying(512) NULL,
        "OriginalValue" character varying(512) NULL,
        "PropertyName" character varying(96) NULL,
        "PropertyTypeFullName" character varying(192) NULL,
        "TenantId" integer NULL,
        "NewValueHash" text NULL,
        "OriginalValueHash" text NULL,
        CONSTRAINT "PK_AbpEntityPropertyChanges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpEntityPropertyChanges_AbpEntityChanges_EntityChangeId" FOREIGN KEY ("EntityChangeId") REFERENCES "AbpEntityChanges" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpPermissions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Name" character varying(128) NOT NULL,
        "IsGranted" boolean NOT NULL,
        "Discriminator" text NOT NULL,
        "RoleId" integer NULL,
        "UserId" bigint NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpPermissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpPermissions_AbpRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AbpRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AbpPermissions_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "AbpRoleClaims" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "RoleId" integer NOT NULL,
        "ClaimType" character varying(256) NULL,
        "ClaimValue" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        CONSTRAINT "PK_AbpRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AbpRoleClaims_AbpRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AbpRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractHistories" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractStatus" integer NOT NULL,
        "AuthorEmail" text NULL,
        "Action" integer NOT NULL,
        "TimeAt" timestamp without time zone NOT NULL,
        "Note" text NULL,
        "ContractId" bigint NOT NULL,
        "MailContent" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractHistories_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractHistories_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractHistories_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractSettings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractId" bigint NOT NULL,
        "SignerName" text NULL,
        "SignerEmail" text NULL,
        "ContractRole" integer NOT NULL,
        "ProcesOrder" integer NULL,
        "Password" text NULL,
        "Color" text NULL,
        "IsComplete" boolean NOT NULL,
        "IsSendMail" boolean NOT NULL,
        "UpdateDate" timestamp without time zone NULL,
        "Role" text NULL,
        "Status" integer NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractSettings_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractSettings_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractSettings_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractSigning" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractId" bigint NOT NULL,
        "Email" text NULL,
        "SignartureBase64" text NULL,
        "SigningResult" text NULL,
        "SignatureId" bigint NULL,
        "TimeAt" timestamp without time zone NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractSigning" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractSigning_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractSigning_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractSigning_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractTemplateSigners" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "Role" text NULL,
        "SignerName" text NULL,
        "SignerEmail" text NULL,
        "ContractRole" integer NOT NULL,
        "ProcesOrder" integer NULL,
        "Color" text NULL,
        "ContractTemplateId" bigint NOT NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractTemplateSigners" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractTemplateSigners_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractTemplateSigners_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractTemplateSigners_ContractTemplates_ContractTemplateId" FOREIGN KEY ("ContractTemplateId") REFERENCES "ContractTemplates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "SignerSignatureSettings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractSettingId" bigint NOT NULL,
        "SignatureTypeId" bigint NOT NULL,
        "SignatureType" integer NOT NULL,
        "Page" integer NOT NULL,
        "IsSigned" boolean NOT NULL,
        "PositionX" real NOT NULL,
        "PositionY" real NOT NULL,
        "Width" real NULL,
        "Height" real NULL,
        "FontSize" real NOT NULL,
        "FontFamily" text NULL,
        "FontColor" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_SignerSignatureSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SignerSignatureSettings_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_SignerSignatureSettings_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_SignerSignatureSettings_ContractSettings_ContractSettingId" FOREIGN KEY ("ContractSettingId") REFERENCES "ContractSettings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE TABLE "ContractTemplateSettings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractTemplateSignerId" bigint NOT NULL,
        "SignatureType" integer NOT NULL,
        "Page" integer NOT NULL,
        "IsSigned" boolean NOT NULL,
        "PositionX" real NOT NULL,
        "PositionY" real NOT NULL,
        "Width" real NULL,
        "Height" real NULL,
        "FontSize" real NOT NULL,
        "FontFamily" text NULL,
        "FontColor" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ContractTemplateSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContractTemplateSettings_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractTemplateSettings_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ContractTemplateSettings_ContractTemplateSigners_ContractTe~" FOREIGN KEY ("ContractTemplateSignerId") REFERENCES "ContractTemplateSigners" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpAuditLogs_TenantId_ExecutionDuration" ON "AbpAuditLogs" ("TenantId", "ExecutionDuration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpAuditLogs_TenantId_ExecutionTime" ON "AbpAuditLogs" ("TenantId", "ExecutionTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpAuditLogs_TenantId_UserId" ON "AbpAuditLogs" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpBackgroundJobs_IsAbandoned_NextTryTime" ON "AbpBackgroundJobs" ("IsAbandoned", "NextTryTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpDynamicEntityProperties_DynamicPropertyId" ON "AbpDynamicEntityProperties" ("DynamicPropertyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE UNIQUE INDEX "IX_AbpDynamicEntityProperties_EntityFullName_DynamicPropertyId~" ON "AbpDynamicEntityProperties" ("EntityFullName", "DynamicPropertyId", "TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpDynamicEntityPropertyValues_DynamicEntityPropertyId" ON "AbpDynamicEntityPropertyValues" ("DynamicEntityPropertyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE UNIQUE INDEX "IX_AbpDynamicProperties_PropertyName_TenantId" ON "AbpDynamicProperties" ("PropertyName", "TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpDynamicPropertyValues_DynamicPropertyId" ON "AbpDynamicPropertyValues" ("DynamicPropertyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityChanges_EntityChangeSetId" ON "AbpEntityChanges" ("EntityChangeSetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityChanges_EntityTypeFullName_EntityId" ON "AbpEntityChanges" ("EntityTypeFullName", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityChangeSets_TenantId_CreationTime" ON "AbpEntityChangeSets" ("TenantId", "CreationTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityChangeSets_TenantId_Reason" ON "AbpEntityChangeSets" ("TenantId", "Reason");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityChangeSets_TenantId_UserId" ON "AbpEntityChangeSets" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpEntityPropertyChanges_EntityChangeId" ON "AbpEntityPropertyChanges" ("EntityChangeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpFeatures_EditionId_Name" ON "AbpFeatures" ("EditionId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpFeatures_TenantId_Name" ON "AbpFeatures" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpLanguages_TenantId_Name" ON "AbpLanguages" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpLanguageTexts_TenantId_Source_LanguageName_Key" ON "AbpLanguageTexts" ("TenantId", "Source", "LanguageName", "Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpNotificationSubscriptions_NotificationName_EntityTypeNam~" ON "AbpNotificationSubscriptions" ("NotificationName", "EntityTypeName", "EntityId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpNotificationSubscriptions_TenantId_NotificationName_Enti~" ON "AbpNotificationSubscriptions" ("TenantId", "NotificationName", "EntityTypeName", "EntityId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpOrganizationUnitRoles_TenantId_OrganizationUnitId" ON "AbpOrganizationUnitRoles" ("TenantId", "OrganizationUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpOrganizationUnitRoles_TenantId_RoleId" ON "AbpOrganizationUnitRoles" ("TenantId", "RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpOrganizationUnits_ParentId" ON "AbpOrganizationUnits" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpOrganizationUnits_TenantId_Code" ON "AbpOrganizationUnits" ("TenantId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpPermissions_RoleId" ON "AbpPermissions" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpPermissions_TenantId_Name" ON "AbpPermissions" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpPermissions_UserId" ON "AbpPermissions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoleClaims_RoleId" ON "AbpRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoleClaims_TenantId_ClaimType" ON "AbpRoleClaims" ("TenantId", "ClaimType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoles_CreatorUserId" ON "AbpRoles" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoles_DeleterUserId" ON "AbpRoles" ("DeleterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoles_LastModifierUserId" ON "AbpRoles" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpRoles_TenantId_NormalizedName" ON "AbpRoles" ("TenantId", "NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE UNIQUE INDEX "IX_AbpSettings_TenantId_Name_UserId" ON "AbpSettings" ("TenantId", "Name", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpSettings_UserId" ON "AbpSettings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenantNotifications_TenantId" ON "AbpTenantNotifications" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenants_CreatorUserId" ON "AbpTenants" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenants_DeleterUserId" ON "AbpTenants" ("DeleterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenants_EditionId" ON "AbpTenants" ("EditionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenants_LastModifierUserId" ON "AbpTenants" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpTenants_TenancyName" ON "AbpTenants" ("TenancyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserAccounts_EmailAddress" ON "AbpUserAccounts" ("EmailAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserAccounts_TenantId_EmailAddress" ON "AbpUserAccounts" ("TenantId", "EmailAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserAccounts_TenantId_UserId" ON "AbpUserAccounts" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserAccounts_TenantId_UserName" ON "AbpUserAccounts" ("TenantId", "UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserAccounts_UserName" ON "AbpUserAccounts" ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserClaims_TenantId_ClaimType" ON "AbpUserClaims" ("TenantId", "ClaimType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserClaims_UserId" ON "AbpUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserLoginAttempts_TenancyName_UserNameOrEmailAddress_Res~" ON "AbpUserLoginAttempts" ("TenancyName", "UserNameOrEmailAddress", "Result");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserLoginAttempts_UserId_TenantId" ON "AbpUserLoginAttempts" ("UserId", "TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE UNIQUE INDEX "IX_AbpUserLogins_ProviderKey_TenantId" ON "AbpUserLogins" ("ProviderKey", "TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserLogins_TenantId_LoginProvider_ProviderKey" ON "AbpUserLogins" ("TenantId", "LoginProvider", "ProviderKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserLogins_TenantId_UserId" ON "AbpUserLogins" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserLogins_UserId" ON "AbpUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserNotifications_UserId_State_CreationTime" ON "AbpUserNotifications" ("UserId", "State", "CreationTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserOrganizationUnits_TenantId_OrganizationUnitId" ON "AbpUserOrganizationUnits" ("TenantId", "OrganizationUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserOrganizationUnits_TenantId_UserId" ON "AbpUserOrganizationUnits" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserRoles_TenantId_RoleId" ON "AbpUserRoles" ("TenantId", "RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserRoles_TenantId_UserId" ON "AbpUserRoles" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserRoles_UserId" ON "AbpUserRoles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUsers_CreatorUserId" ON "AbpUsers" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUsers_DeleterUserId" ON "AbpUsers" ("DeleterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUsers_LastModifierUserId" ON "AbpUsers" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUsers_TenantId_NormalizedEmailAddress" ON "AbpUsers" ("TenantId", "NormalizedEmailAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUsers_TenantId_NormalizedUserName" ON "AbpUsers" ("TenantId", "NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserTokens_TenantId_UserId" ON "AbpUserTokens" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpUserTokens_UserId" ON "AbpUserTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_AbpWebhookSendAttempts_WebhookEventId" ON "AbpWebhookSendAttempts" ("WebhookEventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_Contacts_CreatorUserId" ON "Contacts" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_Contacts_LastModifierUserId" ON "Contacts" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractBase64Images_CreatorUserId" ON "ContractBase64Images" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractBase64Images_LastModifierUserId" ON "ContractBase64Images" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractHistories_ContractId" ON "ContractHistories" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractHistories_CreatorUserId" ON "ContractHistories" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractHistories_LastModifierUserId" ON "ContractHistories" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_Contracts_CreatorUserId" ON "Contracts" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_Contracts_LastModifierUserId" ON "Contracts" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_Contracts_UserId" ON "Contracts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSettings_ContractId" ON "ContractSettings" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSettings_CreatorUserId" ON "ContractSettings" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSettings_LastModifierUserId" ON "ContractSettings" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSigning_ContractId" ON "ContractSigning" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSigning_CreatorUserId" ON "ContractSigning" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractSigning_LastModifierUserId" ON "ContractSigning" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplates_CreatorUserId" ON "ContractTemplates" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplates_LastModifierUserId" ON "ContractTemplates" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSettings_ContractTemplateSignerId" ON "ContractTemplateSettings" ("ContractTemplateSignerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSettings_CreatorUserId" ON "ContractTemplateSettings" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSettings_LastModifierUserId" ON "ContractTemplateSettings" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSigners_ContractTemplateId" ON "ContractTemplateSigners" ("ContractTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSigners_CreatorUserId" ON "ContractTemplateSigners" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_ContractTemplateSigners_LastModifierUserId" ON "ContractTemplateSigners" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_EmailTemplates_CreatorUserId" ON "EmailTemplates" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_EmailTemplates_LastModifierUserId" ON "EmailTemplates" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignatureUsers_CreatorUserId" ON "SignatureUsers" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignatureUsers_LastModifierUserId" ON "SignatureUsers" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignatureUsers_UserId" ON "SignatureUsers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignerSignatureSettings_ContractSettingId" ON "SignerSignatureSettings" ("ContractSettingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignerSignatureSettings_CreatorUserId" ON "SignerSignatureSettings" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    CREATE INDEX "IX_SignerSignatureSettings_LastModifierUserId" ON "SignerSignatureSettings" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230706080910_int_database') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230706080910_int_database', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230720040937_add_contractGuid_column') THEN
    ALTER TABLE "Contracts" ADD "ContractGuid" uuid NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230720040937_add_contractGuid_column') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230720040937_add_contractGuid_column', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230724072422_add_guid_to_ContractSigning') THEN
    ALTER TABLE "ContractSigning" ADD "Guid" uuid NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230724072422_add_guid_to_ContractSigning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230724072422_add_guid_to_ContractSigning', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230726110652_add_signatureType_to_ContractSigning') THEN
    ALTER TABLE "ContractSigning" ADD "SignatureType" integer NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230726110652_add_signatureType_to_ContractSigning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230726110652_add_signatureType_to_ContractSigning', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230801085031_add_valueInput_to_SignerSignatureSettings') THEN
    ALTER TABLE "SignerSignatureSettings" ADD "ValueInput" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230801085031_add_valueInput_to_SignerSignatureSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230801085031_add_valueInput_to_SignerSignatureSettings', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230810080937_add_valueInput_to_ContractTemplateSettings') THEN
    ALTER TABLE "ContractTemplateSettings" ADD "ValueInput" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230810080937_add_valueInput_to_ContractTemplateSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230810080937_add_valueInput_to_ContractTemplateSettings', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230830104224_add_column_for_FeatureMassContract') THEN
    ALTER TABLE "ContractTemplates" ADD "MassType" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230830104224_add_column_for_FeatureMassContract') THEN
    ALTER TABLE "Contracts" ADD "MassGuid" uuid NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230830104224_add_column_for_FeatureMassContract') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230830104224_add_column_for_FeatureMassContract', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230831023128_add_tbl_MassContractTemplateSigner') THEN
    CREATE TABLE "MassContractTemplateSigners" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "ContractTemplateSignerId" bigint NOT NULL,
        "SignerName" text NULL,
        "SignerEmail" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_MassContractTemplateSigners" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MassContractTemplateSigners_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_MassContractTemplateSigners_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_MassContractTemplateSigners_ContractTemplateSigners_Contrac~" FOREIGN KEY ("ContractTemplateSignerId") REFERENCES "ContractTemplateSigners" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230831023128_add_tbl_MassContractTemplateSigner') THEN
    CREATE INDEX "IX_MassContractTemplateSigners_ContractTemplateSignerId" ON "MassContractTemplateSigners" ("ContractTemplateSignerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230831023128_add_tbl_MassContractTemplateSigner') THEN
    CREATE INDEX "IX_MassContractTemplateSigners_CreatorUserId" ON "MassContractTemplateSigners" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230831023128_add_tbl_MassContractTemplateSigner') THEN
    CREATE INDEX "IX_MassContractTemplateSigners_LastModifierUserId" ON "MassContractTemplateSigners" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230831023128_add_tbl_MassContractTemplateSigner') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230831023128_add_tbl_MassContractTemplateSigner', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230906045515_add_Column_MassGuid_tbl_ContractSetting') THEN
    ALTER TABLE "ContractSettings" ADD "SignerMassGuid" uuid NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230906045515_add_Column_MassGuid_tbl_ContractSetting') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230906045515_add_Column_MassGuid_tbl_ContractSetting', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919045839_add_Columns_For_MassWordAutoFill_MassTemplate') THEN
    ALTER TABLE "ContractTemplates" ADD "MassField" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919045839_add_Columns_For_MassWordAutoFill_MassTemplate') THEN
    ALTER TABLE "ContractTemplates" ADD "MassWordContent" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919045839_add_Columns_For_MassWordAutoFill_MassTemplate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230919045839_add_Columns_For_MassWordAutoFill_MassTemplate', '6.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231023102314_add_apiKeyTBL') THEN
    CREATE TABLE "ApiKeys" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NULL,
        "UserId" bigint NOT NULL,
        "Value" text NULL,
        "CreationTime" timestamp without time zone NOT NULL,
        "CreatorUserId" bigint NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "LastModifierUserId" bigint NULL,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint NULL,
        "DeletionTime" timestamp without time zone NULL,
        CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ApiKeys_AbpUsers_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "AbpUsers" ("Id"),
        CONSTRAINT "FK_ApiKeys_AbpUsers_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "AbpUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231023102314_add_apiKeyTBL') THEN
    CREATE INDEX "IX_ApiKeys_CreatorUserId" ON "ApiKeys" ("CreatorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231023102314_add_apiKeyTBL') THEN
    CREATE INDEX "IX_ApiKeys_LastModifierUserId" ON "ApiKeys" ("LastModifierUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231023102314_add_apiKeyTBL') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231023102314_add_apiKeyTBL', '6.0.7');
    END IF;
END $EF$;
COMMIT;

